#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

#include "ceu_types.h"

#include "SDL.h"
//#include "SDL2/SDL_image.h"
//#include "SDL2/SDL_mixer.h"
//#include "SDL2/SDL_ttf.h"
//#include "SDL2/SDL_opengl.h"


s32 WCLOCK_nxt;
#define ceu_out_wclock_set(us) WCLOCK_nxt = us;
#define ceu_out_assert(X) assert(X)
#define ceu_out_log(m,s)


//extern void boxRGBA(int x1, int y1, int x2, int y2, uint8_t r, uint8_t g, uint8_t b, uint8_t a);

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"


static byte CEU_DATA[sizeof(CEU_Main)];
static tceu_app app;

int last = 1;

int async_check() {
	#ifdef CEU_ASYNCS
		if (app.pendingAsyncs) {
			return 1;
		}
	#endif
	return 0;
}

//SDL_Event evt;
//u32 old = SDL_GetTicks();
u32 old = 0;

int async_call() {
	ceu_sys_go(&app, CEU_IN__ASYNC, NULL);
	#ifdef CEU_RET
	if (! app.isAlive) {
		if (async_check() == 1) {
			printf("%d\n", app.ret);
			return 1;
		}
		else if (last == 1) {
			last = 0;
			printf("%d\n", app.ret);
			return 1;
		}
	}
	#endif
	return 0;
}


void update(s32 time) {

	s32 dt_us = time;
	ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);

	#ifdef CEU_IN_SDL_DT
	u32 dt_ms = dt_us / 1000;
	ceu_sys_go(&app, CEU_IN_SDL_DT, &dt_ms);
	#endif

	#ifdef CEU_IN_SDL_REDRAW
	ceu_sys_go(&app, CEU_IN_SDL_REDRAW, NULL);
	#endif


	s32 prev = WCLOCK_nxt;
	while (WCLOCK_nxt <= 0) {
		s32 dt_us = 0;
		ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);

		#ifdef CEU_IN_SDL_DT
		ceu_sys_go(&app, CEU_IN_SDL_DT, &dt_us);
		#endif

		#ifdef CEU_IN_SDL_REDRAW
		ceu_sys_go(&app, CEU_IN_SDL_REDRAW, NULL);
		#endif

		//When there are no timed events
		if (WCLOCK_nxt == prev) {
			WCLOCK_nxt = 1;

		}
	}

}

int convert(int keycode) {
	if( keycode >= 65 && keycode <= 90)
		keycode += 32;
	return keycode;
}

void key_down(int keycode) {

	SDL_Event event;

	//to convert from the upercase value of javascript to the lowercase value of SDLK
	keycode = convert(keycode);

	event.type = SDL_KEYDOWN;
	event.key.state = SDL_PRESSED;
	event.key.keysym.sym = keycode;

	SDL_Event* evtp = &event;

	#ifdef CEU_IN_SDL_KEYDOWN
	ceu_sys_go(&app, CEU_IN_SDL_KEYDOWN, &evtp);
	#endif
}

void key_up(int keycode) {

	SDL_Event event;

	//to convert from the upercase value of javascript to the lowercase value of SDLK
	keycode = convert(keycode);

	event.type = SDL_KEYUP;
	event.key.state = SDL_RELEASED;
	event.key.keysym.sym = keycode;

	SDL_Event* evtp = &event;

	#ifdef CEU_IN_SDL_KEYUP
	ceu_sys_go(&app, CEU_IN_SDL_KEYUP, &evtp);
	#endif
}

void mouse_down(int which, int x, int y) {
	SDL_Event event;

	event.type = SDL_MOUSEBUTTONDOWN;
	event.button.state = SDL_PRESSED;
	event.button.which = which;
	event.button.x = x;
	event.button.y = y;

	SDL_Event* evtp = &event;

	#ifdef CEU_IN_SDL_MOUSEBUTTONDOWN
	ceu_sys_go(&app, CEU_IN_SDL_MOUSEBUTTONDOWN, &evtp);
	#endif

}

void mouse_up(int which, int x, int y) {
	SDL_Event event;

	event.type = SDL_MOUSEBUTTONUP;
	event.button.state = SDL_RELEASED;
	event.button.which = which;
	event.button.x = x;
	event.button.y = y;

	SDL_Event* evtp = &event;

	#ifdef CEU_IN_SDL_MOUSEBUTTONUP
	ceu_sys_go(&app, CEU_IN_SDL_MOUSEBUTTONUP, &evtp);
	#endif

}

void mouse_move(int x, int y) {
	SDL_Event event;

	event.type = SDL_MOUSEMOTION;
	event.motion.x = x;
	event.motion.y = y;

	SDL_Event* evtp = &event;

	#ifdef CEU_IN_SDL_MOUSEMOTION
	ceu_sys_go(&app, CEU_IN_SDL_MOUSEMOTION, &evtp);
	#endif
}


void disable_events() {
	//SDL_EventState(SDL_TEXTINPUT, SDL_DISABLE);
	//SDL_EventState(SDL_KEYDOWN, SDL_DISABLE);
	//SDL_EventState(SDL_KEYUP, SDL_DISABLE);
	
}

void enable_events() {
	
	//SDL_EventState(SDL_TEXTINPUT, SDL_ENABLE);
	//SDL_EventState(SDL_KEYDOWN, SDL_ENABLE);
	//SDL_EventState(SDL_KEYUP, SDL_ENABLE);
	
}

void begin() {
	memset(CEU_DATA, 0, sizeof(CEU_Main));
	app.data = (tceu_org*) &CEU_DATA;
	app.init = &ceu_app_init;
	app.init(&app);

	//SDL_Init(SDL_INIT_EVERYTHING);
}

