#include <stdio.h>
#include <stdlib.h>
#include <emscripten.h>
#include "ceu_types.h"

s32 WCLOCK_nxt;
#define ceu_out_wclock_set(us) WCLOCK_nxt = us;
#define ceu_out_assert(X) assert(X)
#define ceu_out_log(X) printf("%s\n", X)

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"


static byte CEU_DATA[sizeof(CEU_Main)];
static tceu_app app;


void update(s32 time) {

	s32 dt_us = time * 1000;
	ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);

	while (WCLOCK_nxt <= 0) {
		s32 dt_us = 0;
		ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);
	}

	//ceu_sys_go( &app, CEU_IN__ASYNC, NULL );
	//u32 us = 100000;
	//ceu_sys_go( &app, CEU_IN__WCLOCK, &us );
}

void begin() {
	memset(CEU_DATA, 0, sizeof(CEU_Main));
	app.data = (tceu_org*) &CEU_DATA;
	app.init = &ceu_app_init;
	app.init(&app);
}

int main() {
	EM_ASM( _begin() );
}
