#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

#include "ceu_types.h"

#include "SDL2/SDL.h"
//#include "SDL2/SDL_image.h"
//#include "SDL2/SDL_mixer.h"
//#include "SDL2/SDL_ttf.h"
//#include "SDL2/SDL_opengl.h"


s32 WCLOCK_nxt;
#define ceu_out_wclock_set(us) WCLOCK_nxt = us;
#define ceu_out_assert(X) assert(X)
#define ceu_out_log(m,s)

// This is the C code generated by the Ceu compiler
#include "_ceu_app.c"


static byte CEU_DATA[sizeof(CEU_Main)];
static tceu_app app;

int last = 1;

int async_check() {
	#ifdef CEU_ASYNCS
		if (app.pendingAsyncs) {
			return 1;
		}
	#endif
	return 0;
}

SDL_Event evt;
//u32 old = SDL_GetTicks();
u32 old = 0;

void new_draw(s32 dt_us) {

	u32 dt_ms = dt_us / 1000;


	ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);
	#ifdef CEU_IN_SDL_DT
	ceu_sys_go(&app, CEU_IN_SDL_DT, &dt_ms);
	#endif
	ceu_sys_go(&app, CEU_IN_SDL_REDRAW, NULL);
}

void key_down(int keycode) {

	SDL_Event event;

	//to convert from the upercase value of javascript to the lowercase value of SDLK
	if( keycode >= 65 && keycode <= 90)
		keycode += 32;

	event.type = SDL_KEYDOWN;
	event.key.state = SDL_PRESSED;
	event.key.keysym.sym = keycode;

	SDL_Event* evtp = &event;

	#ifdef CEU_IN_SDL_KEYDOWN
	ceu_sys_go(&app, CEU_IN_SDL_KEYDOWN, &evtp);
	#endif
}


int ceu_draw(u32 oldee) {
	   s32 tm = -1;

    #ifdef CEU_WCLOCKS
            if (WCLOCK_nxt != CEU_WCLOCK_INACTIVE)
                tm = WCLOCK_nxt / 1000;
    #endif
    #ifdef CEU_ASYNCS
            if (app.pendingAsyncs) {
                tm = 0;
            }
    #endif


        //SDL_EventState(SDL_FINGERMOTION, SDL_IGNORE);



        int has = SDL_WaitEventTimeout(&evt, tm);

//#ifndef SIMULATION_TEST

        u32 now = SDL_GetTicks();
        s32 dt_ms = (now - old);
        assert(dt_ms >= 0);
        old = now;


        s32 dt_us = dt_ms*1000;


#ifdef CEU_WCLOCKS
    #if ! (defined(CEU_IN_SDL_DT) || defined(CEU_IN_SDL_DT_))
                if (WCLOCK_nxt != CEU_WCLOCK_INACTIVE)
                {
                    //redraw = WCLOCK_nxt <= dt_us;
    #endif

   

                ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);
    #ifdef CEU_RET
                    if (! app.isAlive)
                        return 0;
    #endif
                while (WCLOCK_nxt <= 0) {
                    s32 dt_us = 0;
                    ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);
    #ifdef CEU_RET
                        if (! app.isAlive)
                            return 0;
    #endif
                }

    #if ! (defined(CEU_IN_SDL_DT) || defined(CEU_IN_SDL_DT_))
                }
    #endif
#endif



#ifdef CEU_IN_SDL_DT
                ceu_sys_go(&app, CEU_IN_SDL_DT, &dt_ms);
    #ifdef CEU_RET
                if (! app.isAlive)
                    return 0;
    #endif
            //redraw = 1;
#endif

        // OTHER EVENTS
        if (has)
        {
            int handled = 1;        // =1 for defined events
            SDL_Event* evtp = &evt;
            switch (evt.type) {
                case SDL_QUIT:


#ifdef CEU_IN_SDL_QUIT
                    ceu_sys_go(&app, CEU_IN_SDL_QUIT, &evtp);
#endif
                    break;
                case SDL_WINDOWEVENT:

#ifdef CEU_IN_SDL_WINDOWEVENT
                    ceu_sys_go(&app, CEU_IN_SDL_WINDOWEVENT, &evtp);
#endif
                    break;
                case SDL_KEYDOWN:

#ifdef CEU_IN_SDL_KEYDOWN
                    ceu_sys_go(&app, CEU_IN_SDL_KEYDOWN, &evtp);
#endif
                    break;
                case SDL_KEYUP:

#ifdef CEU_IN_SDL_KEYUP
                    ceu_sys_go(&app, CEU_IN_SDL_KEYUP, &evtp);
#endif
                    break;
                case SDL_TEXTINPUT:

#ifdef CEU_IN_SDL_TEXTINPUT
                    ceu_sys_go(&app, CEU_IN_SDL_TEXTINPUT, &evtp);
#endif
                    break;
                case SDL_TEXTEDITING:

#ifdef CEU_IN_SDL_TEXTEDITING
                    ceu_sys_go(&app, CEU_IN_SDL_TEXTEDITING, &evtp);
#endif
                    break;
                case SDL_MOUSEMOTION:

#ifdef CEU_IN_SDL_MOUSEMOTION
                    ceu_sys_go(&app, CEU_IN_SDL_MOUSEMOTION, &evtp);
#endif
                    break;
                case SDL_MOUSEBUTTONDOWN:

#ifdef CEU_IN_SDL_MOUSEBUTTONDOWN
                    ceu_sys_go(&app, CEU_IN_SDL_MOUSEBUTTONDOWN, &evtp);
#endif
                    break;
                case SDL_MOUSEBUTTONUP:

#ifdef CEU_IN_SDL_MOUSEBUTTONUP
                    ceu_sys_go(&app, CEU_IN_SDL_MOUSEBUTTONUP, &evtp);
#endif
                    break;
                case SDL_FINGERDOWN:

#ifdef CEU_IN_SDL_FINGERDOWN
                    ceu_sys_go(&app, CEU_IN_SDL_FINGERDOWN, &evtp);
#endif
                    break;
                case SDL_FINGERUP:

#ifdef CEU_IN_SDL_FINGERUP
                    ceu_sys_go(&app, CEU_IN_SDL_FINGERUP, &evtp);
#endif
                    break;
                case SDL_FINGERMOTION:

#ifdef CEU_IN_SDL_FINGERMOTION
                    ceu_sys_go(&app, CEU_IN_SDL_FINGERMOTION, &evtp);
#endif
                    break;

                default:
                    handled = 0;    // undefined event
            }
#ifdef CEU_RET
            if (! app.isAlive) return 0;
#endif
            //redraw = redraw || handled;
        }


#ifdef CEU_IN_SDL_REDRAW

            ceu_sys_go(&app, CEU_IN_SDL_REDRAW, NULL);
    #ifdef CEU_RET
                if (! app.isAlive)
                    return 0;
    #endif

#endif


//#endif  /* SIMULATION_TEST */




/* TODO: "_" events */
#ifdef CEU_ASYNCS
        if (app.pendingAsyncs) {
            ceu_sys_go(&app, CEU_IN__ASYNC, NULL);
#ifdef CEU_RET
            if (! app.isAlive)
                return 0;
#endif
        }
#endif
    
return 1;
}

int async_call() {
	ceu_sys_go(&app, CEU_IN__ASYNC, NULL);
	#ifdef CEU_RET
	if (! app.isAlive) {
		if (async_check() == 1) {
			printf("%d\n", app.ret);
			return 1;
		}
		else if (last == 1) {
			last = 0;
			printf("%d\n", app.ret);
			return 1;
		}
	}
	#endif
	return 0;
}


void update(s32 time) {

	s32 dt_us = time;
	ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);


	s32 prev = WCLOCK_nxt;
	while (WCLOCK_nxt <= 0) {
		s32 dt_us = 0;
		ceu_sys_go(&app, CEU_IN__WCLOCK, &dt_us);

		//DRAW FUNCTION
		//ceu_sys_go(&app, CEU_IN_SDL_REDRAW, NULL);

		//When there are no timed events
		if (WCLOCK_nxt == prev) {
			WCLOCK_nxt = 1;

		}
	}

}

void begin() {
	memset(CEU_DATA, 0, sizeof(CEU_Main));
	app.data = (tceu_org*) &CEU_DATA;
	app.init = &ceu_app_init;
	app.init(&app);

	SDL_Init(SDL_INIT_EVERYTHING);
}

